---
title: Identificação de problemas
author: CISM
fig_height: 2.6
fig_width: 4
output:
  html_document:
    toc: true
    toc_float: true
    theme: yeti
---
```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = FALSE}
# No scientific notation
options(scipen=999)

# Packages 
library(xtable)
library(knitr)
library(ggplot2) 
# library(dplyr)
library(rgeos)
library(RColorBrewer)
library(Rmisc)
# Libraries
library(rgdal)
library(raster)
library(sp)
library(leaflet)
library(ggmap)
library(readxl)
library(dplyr)
library(readr)

# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, # Render report, even with errors
               cache = F)

# Helpers
source('lib/get_zambezia.R')
source('lib/helpers.R')
```

```{r setup, include=FALSE, echo = FALSE}
library(knitr)
knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knit_child(text = options$code)
})
```


# Introduction

This document is meant to help in the identification of problems with the Mopeia census data. It is meant for internal use.

```{r}
#### READ IN AND CLEAN UP DATA

# Read in final dataset, as given by Orvahlo on October 12, 2016
census <- read_excel('dropbox/20161012/household.xlsx')

# Get more nicely named geographic coordinate column names
census$lat <- census$y <- census$latitude <- census$gpc_lat
census$lon <- census$lng <- census$longitude <-census$x <- census$gpc_lng

# Get a shapefile for Mozambique
moz <- raster::getData('GADM', country = 'MOZ', level = 3)
moz2 <- raster::getData('GADM', country = 'MOZ', level = 2)

# Get a village number
census$village_number <- 
  as.numeric(lapply(strsplit(census$houseno_rev, split = '-'), function(x){x[2]}))

# Create a spatial version of census
census_spatial <- census
coordinates(census_spatial) <- ~x+y
proj4string(census_spatial) <- proj4string(moz)

# Subset the shapefile just to Zambezia
zam <- moz[moz@data$NAME_1 == 'Zambezia',]

# Subset further to just Mopeia
mop <- moz2[moz2@data$NAME_2 == 'Mopeia',]

# Save the original proj4string
original_proj4string <- proj4string(moz)

# Prepare ggmap-compatible objects
zam_fortified <- fortify(zam, id = ID_3)
mop_fortified <- fortify(mop, id = ID_3)
zam_gg <- get_map(location = c(lon = mean(census$lon, na.rm = TRUE),
                               lat = mean(census$lat, na.rm = TRUE)),
                  maptype = 'satellite')
mop_gg <- get_map(location = c(lon = mean(census$lon, na.rm = TRUE),
                               lat = mean(census$lat, na.rm = TRUE)),
                  maptype = 'satellite')

# Switch to a projected format
# Project
census_spatial <- spTransform(census_spatial, CRS( "+init=epsg:3347" ) )
mop <- spTransform(mop, CRS("+init=epsg:3347"))
# Later, we can switch back to lat/long:
census_spatial_ll <- spTransform(census_spatial, CRS("+init=epsg:4326"))
mop_ll  <- spTransform(mop, CRS("+init=epsg:4326"))
# proj4string(mop_ll) <- proj4string(zam)

# Get the most prevalent village name for each village number
census_villages <-
  census %>%
  dplyr::group_by(village_number, village) %>% 
  tally %>%
  group_by(village_number) %>%
  summarise(correct_village_name = village[which(n == max(n))][1])
```



```{r}
# Make a dataframe of just villages (with cluster assignments)
village_df <- make_village_df(census = census)

# Identify problems
identify_problems()
```

# Village maps

The below maps show each village, as well as the boundary of that village's area.

```{r, eval = TRUE}
# 
# village_list <- list()
# for (i in 1:nrow(village_df)){
#   village_list[[i]] <- village_df[i,]
# }


maps <- lapply(village_df$row_number, function(x){
  leaflet_village(x)
})

htmltools::tagList(maps)
# for(i in 1:3){
# # for(i in 1:nrow(village_df)){
#   this_village_number <- village_df$village_number[i]
#    # Get the points only
#   sub_census <- census_spatial_ll[which(census_spatial_ll$village_number == this_village_number),]
#   # Get the border
#   border <- gConvexHull(sub_census)
# 
#   leaflet_village(the_data = sub_census,
#                   the_border = border) 
#   
#   #   # Plot Mopeia
#   # plot(mop_ll)
#   # # Plot the border
#   # plot(border, add = TRUE, col = adjustcolor(color, alpha.f = 0.3),
#   #      border = adjustcolor(color, alpha.f = 0.8))
#   # # Add the points
#   # points(sub_census,
#   #        pch = '.',
#   #        col = adjustcolor(color, alpha.f = 0.6))
#   # # Add title
#   # title(main = paste0('Village number: ', unique_village_numbers[i]))
# }
```

# Table of all houses and problems

What follows is a table of all households, and whether they are flagged as incorrect or not.

```{r}
x <- census %>%
  mutate(suspected = houseno_rev %in% incorrect_houses) %>%
  mutate(suspected = ifelse(suspected, 'suspected', 'okay')) %>%
  dplyr::select(village_number,
                houseno_rev,
                suspected,
                administrative_post,
                local_village_name) %>%
  arrange(village_number)
x$local_village_name <- stringr::str_replace_all(x$local_village_name,"[^[:graph:]]", " ")
DT::datatable(x)

# Table for Edgar, 13 October 2016
# Bring problems into spatial
census_spatial_ll$suspeito <- 
  ifelse(census_spatial_ll$houseno_rev %in% incorrect_houses,
                         'Suspeito',
                         'OK') 

edgar <- census %>%
  dplyr::select(village_number,
                houseno_rev,
                administrative_post,
                locality,
                village,
                local_village_name,
                dinq,
                lng,
                lat) %>%
  rename(date_survey = dinq)
edgar$suspeito <- ifelse(edgar$houseno_rev %in% incorrect_houses,
                         'Suspeito',
                         'OK') 
edgar <- edgar %>%
  arrange(desc(suspeito))

edgar$url <- paste0('www.economicsofmalaria.com/pngs/', edgar$houseno_rev, '.png')

write_csv(edgar, '~/Desktop/table_for_edgar.csv')

# Generate pngs too
for (i in 1:nrow(edgar)){
  # This village
  this_village_number <- edgar$village_number[i]
  
  # This villager
  this_villager <- census_spatial_ll[census_spatial_ll$houseno_rev == edgar$houseno_rev[i],]
  
  # Other villagers
  other_villagers <- census_spatial_ll[which(census_spatial_ll$village_number == this_village_number),]  
  
  # Get correct villagers
  correct_villagers <- other_villagers[which(other_villagers$suspeito == 'OK'),]
  # Get border
  border <- gConvexHull(other_villagers)
  correct_border <- gConvexHull(correct_villagers)
  
  
  file_name <- paste0('/home/joebrew/Documents/joebrew.github.io/pngs/', edgar$houseno_rev[i], '.png')
  png(file_name, width = 480,
      height = 960)
  
  par(mfrow = c(2,1))
  plot(mop_ll)  
  points(other_villagers, pch = '.',
         col  = ifelse(other_villagers$suspeito == 'OK',
                       'darkgreen',
                       'red'))
  plot(border, col = adjustcolor('red', alpha.f = 0.2), add = TRUE,
       border = adjustcolor('red', alpha.f = 0.2))
  if(nrow(correct_villagers)> 0){
    plot(correct_border, 
       col = adjustcolor('darkgreen', alpha.f = 0.2), add = TRUE,
       border = adjustcolor('darkgreen', alpha.f = 0.2))
  }
  
  points(this_villager, col = 'black')
  points(this_villager, col = 'black', pch = 3)
  title(main = 'Zoom out')
    title(sub = paste0('Village number ', this_village_number))
  
  legend('topleft',
         pch = 1,
         col = c('darkgreen',
                 'red',
                 'black'),
         legend = c('Casas OK',
                    'Casas suspeitas',
                    'Esta casa'),
         pt.cex = 0.8,
         cex = 0.8,
         bty = 'n')
  legend('bottomleft',
         lty = 1,
          col = c('darkgreen',
         'red'),
 legend = c('Fronteira corregida',
            'Fronteira original'),
 cex = 0.8,
 bty = 'n')
  
  plot(other_villagers, pch = '.',
         col  = ifelse(other_villagers$suspeito == 'OK',
                       'darkgreen',
                       'red'))
  plot(border, col = adjustcolor('red', alpha.f = 0.2), add = TRUE,
       border = adjustcolor('red', alpha.f = 0.2))
  if(nrow(correct_villagers) > 0){
    plot(correct_border, 
       col = adjustcolor('darkgreen', alpha.f = 0.2), add = TRUE,
       border = adjustcolor('darkgreen', alpha.f = 0.2))
  }
  
  points(this_villager, col = 'black')
  points(this_villager, col = 'black', pch = 3)
  title(main = paste0('House number ', this_villager$houseno_rev),
        outer = TRUE, line = -1)
  title (main = 'Zoom in')
  title(sub = paste0('Village number ', this_village_number))
  
  legend('topleft',
         pch = 1,
         col = c('darkgreen',
                 'red',
                 'black'),
         legend = c('Casas OK',
                    'Casas suspeitas',
                    'Esta casa'),
         pt.cex = 0.8,
         cex = 0.8,
         bty = 'n')
  legend('bottomleft',
         lty = 1,
          col = c('darkgreen',
         'red'),
 legend = c('Fronteira corregida',
            'Fronteira original'),
 cex = 0.8,
 bty = 'n')
  
  
  par(mfrow = c(1,1))
  dev.off()
  message(i)
}

```

<!-- ## Addressing errors -->

<!-- In order to address errors, we simply remove the `r length(incorrect_houses)` houses we suspect to be incorrectly classified.   -->

```{r, eval = FALSE}
# FILTERING OUT THOSE INCORRECT HOUSES
census <- census %>%
  filter(!houseno_rev %in% incorrect_houses)

# Create a spatial version of census
census_spatial <- census
coordinates(census_spatial) <- ~x+y
proj4string(census_spatial) <- proj4string(moz)
# Switch to a projected format
# Project
census_spatial <- spTransform(census_spatial, CRS( "+init=epsg:3347" ) )
# Later, we can switch back to lat/long:
census_spatial_ll <- spTransform(census_spatial, CRS("+init=epsg:4326"))
```


```{r, eval = FALSE}
# Remove those observations with no coordinates
census <- census %>%
  filter(!is.na(lng), !is.na(lat))

# Get centroids
village_df <-
  village_df %>%
  left_join(census %>%
    group_by(village_number) %>%
    summarise(x_centroid = mean(lng, na.rm = TRUE),
              y_centroid = mean(lat, na.rm = TRUE)))

# Remove the villages with no coordinates
village_df <- 
  village_df %>%
  filter(!is.na(x_centroid),
         !is.na(y_centroid))

# Get distances between villages
distances <- spDists(x = as.matrix(village_df %>% dplyr::select(x_centroid, y_centroid)),
        longlat = TRUE,
        diagonal = FALSE)

# Bring cluster type into census
census <- census %>% 
  left_join(village_df %>%
              dplyr::select(village_number, cluster),
            by = 'village_number')
# Create a spatial version of census
census_spatial <- census
coordinates(census_spatial) <- ~x+y
proj4string(census_spatial) <- proj4string(moz)
# Switch to a projected format
# Project
census_spatial <- spTransform(census_spatial, CRS( "+init=epsg:3347" ) )
# Later, we can switch back to lat/long:
census_spatial_ll <- spTransform(census_spatial, CRS("+init=epsg:4326"))
```
